heroku_database: b2cf313e5c854b:f227b197@us-cdbr-east-06.cleardb.net/heroku_9e1cce48c06f67b?reconnect=true
heroku_username: b2cf313e5c854b
heroku_password: f227b197

localhost_database: localhost:3306/argviewer
localhost_username: root
localhost_password: password

server:
  port: 9000

debug: true

springdoc:
  api-docs:
    path: /api-docs

spring:
  datasource:
    url: jdbc:mysql://${localhost_database}
    username: ${localhost_username}
    password: ${localhost_password}
  jpa:
    show-sql: true
    defer-datasource-initialization: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:${server.port}/auth/realms/baeldung
          jwk-set-uri: http://localhost:${server.port}/auth/realms/baeldung/protocol/openid-connect/certs
  properties:
    hibernate:
      format_sql: true
      ddl-auto: update
  output:
    ansi:
      enabled: always

logging:
    level:
      org:
        hibernate:
          SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE