heroku:
  username: b2cf313e5c854b
  password: f227b197
  database: ${heroku.username}:${heroku.password}@us-cdbr-east-06.cleardb.net/heroku_9e1cce48c06f67b?reconnect=true

localhost:
  username: root
  password: password
  database: ${localhost.username}:${localhost.password}@localhost:3306/argviewer

server:
  port: 9000
  ssl:
    key-store-type: PKCS12
    key-store: classpath:keystore/argviewer.p12
    key-store-password: password
    key-alias: argviewer
  ssl-enabled: false

trust:
  store: classpath:keystore/argviewer.p12
  store.password: password

springdoc:
  api-docs:
    path: /api-docs

spring:
  datasource:
    url: jdbc:mysql://${heroku.database}
    username: ${heroku.username}
    password: ${heroku.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MySQL55Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  output:
    ansi:
      enabled: always