heroku:
  database: b2cf313e5c854b:f227b197@us-cdbr-east-06.cleardb.net/heroku_9e1cce48c06f67b?reconnect=true
  username: b2cf313e5c854b
  password: f227b197

localhost:
  database: localhost:3306/argviewer
  username: root
  password: password

server:
  port: 9000

debug: true

springdoc:
  api-docs:
    path: /api-docs

spring:
  datasource:
    url: jdbc:mysql://${localhost.database}
    username: ${localhost.username}
    password: ${localhost.password}
  jpa:
    show-sql: true
    defer-datasource-initialization: true
  properties:
    hibernate:
      format_sql: true
      ddl-auto: update
  output:
    ansi:
      enabled: always

logging:
    level:
      org:
        hibernate:
          SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE