heroku:
  database: b2cf313e5c854b:f227b197@us-cdbr-east-06.cleardb.net/heroku_9e1cce48c06f67b?reconnect=true
  username: b2cf313e5c854b
  password: f227b197

localhost:
  database: localhost:3306/argviewer
  username: root
  password: password

server:
  port: 9000
  ssl:
    key-store-type: PKCS12
    key-store: classpath:keystore/argviewer.p12
    key-store-password: password
    key-alias: argviewer
  ssl-enabled: true

trust:
  store: classpath:keystore/argviewer.p12
  store.password: password

springdoc:
  api-docs:
    path: /api-docs

spring:
  datasource:
    url: jdbc:mysql://${heroku.database}
    username: ${heroku.username}
    password: ${heroku.password}
  jpa:
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  output:
    ansi:
      enabled: always