google-cloud:
  username: ${DB_USERNAME}
  password: ${DB_PASSWORD}
  database: ${DB_HOST}

server:
  port: ${PORT}

springdoc:
  api-docs:
    path: /api-docs

spring:
  datasource:
    url: jdbc:mysql://${google-cloud.database}
    username: ${google-cloud.username}
    password: ${google-cloud.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  output:
    ansi:
      enabled: always